-- sta se monitorise
select * from sys.server_event_notifications
go
drop event notification AUDIT_SERVER_EVENTS
  on server
go
-- PRETPLACIVANJE NA DOGADJAJ  audit_table --------------------------------------
--
use MSDB
create event notification AUDIT_SERVER_EVENTS
  on server
  for 
 CREATE_TABLE
,ALTER_TABLE
,DROP_TABLE
,CREATE_INDEX
-- ,ALTER_INDEX		-	ne pratimo zbog ALTER INDEX blabla ON tblbla REBUILD WITH (FILLFACTOR = 80, ONLINE = ON)
,DROP_INDEX
,CREATE_SYNONYM
,DROP_SYNONYM
,CREATE_VIEW
,ALTER_VIEW
,DROP_VIEW
,CREATE_PROCEDURE
,ALTER_PROCEDURE
,DROP_PROCEDURE
,CREATE_FUNCTION
,ALTER_FUNCTION
,DROP_FUNCTION
,CREATE_TRIGGER
,ALTER_TRIGGER
,DROP_TRIGGER
,CREATE_USER
,ALTER_USER
,DROP_USER
,CREATE_ROLE
,ALTER_ROLE
,DROP_ROLE
,CREATE_APPLICATION_ROLE
,ALTER_APPLICATION_ROLE
,DROP_APPLICATION_ROLE
,GRANT_SERVER
,DENY_SERVER
,GRANT_DATABASE
,DENY_DATABASE
,CREATE_PARTITION_FUNCTION
,ALTER_PARTITION_FUNCTION
,DROP_PARTITION_FUNCTION
,CREATE_XML_INDEX
,ADD_ROLE_MEMBER
,DROP_ROLE_MEMBER
,ADD_SERVER_ROLE_MEMBER
,DROP_SERVER_ROLE_MEMBER
,CREATE_DATABASE
,ALTER_DATABASE
,DROP_DATABASE
  to service 'AUDIT_SERVER_SERVICE', 'current database'  

go

